### ISSUE TITLE
Mehak blog post map review

### ISSUE THREAD

**Issue by makella** [CartoDB/cartography#1]
To review the maps for her blog on H1B visas

We are finalizing a blogpost analyzing the bill for H-1B visas. The final text for the post is here: https://docs.google.com/document/d/1BkgAFhUgcfBTVh9DYRAXDDJ4oOB-WlO_tscLGUlnJL8/edit
And the maps are here:
Header: https://team.carto.com/u/mehak-carto/builder/c3f5efc4-0995-11e7-b8b8-0e233c30368f/embed
https://team.carto.com/u/mehak-carto/builder/05a9137e-6659-412f-899a-2aa1c2d8675a/embed
https://team.carto.com/u/mehak-carto/builder/b17c0931-50e0-4fa6-8a88-90b91f46681a/embed
https://team.carto.com/u/mehak-carto/builder/6552e653-d487-4c03-8967-ecf5e6f89b49/embed
https://team.carto.com/u/mehak-carto/builder/0fa2a0e3-8a32-4a10-82db-15146dcd3dc3/embed
https://team.carto.com/u/mehak-carto/builder/4956fee0-9940-4935-9a3a-a53edc2ee48d/embed

**Comment by makella** [comment]
@mehak-sachdeva

At first pass, I think the maps look good. I don't have access to the blog post text so once I can see that it will be easier for me to compare the text to the maps. 

In the meantime, I have a few comments:
- I like the effect of the lines on the first map, but it would be more useful if they updated along with the filtering of data through the widgets. Is the intent to show the global reach of visas to the US? If so, you may want to consider varying the line width or some other effect that shows that.

- I like that you stayed consistent with symbology for maps 2-5,  but in order to better understand what they symbology represents, you need some kind of legend. It is difficult to understand what the two different colored proportional symbols represent. 
  - one idea here is to modify the colors of the widget bars to match the symbology on the map. For example, use the red and teal to color the bars on the widgets of the variables they represent. And on the first map, the brown and teal. Obviously, another choice is to configure a default legend.

- Second, you need to configure the pop-ups better. Using the default attributes like (`revenue_required`) isn't very descriptive. I would take advantage of the ability to modify the attribute titles for the popups.

- Third, (and I'm sure you are aware), when you use compositing operations, the map rarely matches the Auto-style colors that draw. I'm not sure if you are using Auto-style in your blog text, but something to be aware of if you are.

Let me know if you have any questions. 

Overall, the maps are really nice and I look forward to reading the blog!

**Comment by mehak-sachdeva** [comment]
These are all great suggestions @makella - thank you so much! I will make the changes today. Sorry you did not have access to the text but I feel the maps should be complete irrespective of that too. I will incorporate your ideas - love the one about coloring widget bars with the color of the symbols! I was struggling to figure how best to use a legend.
Thank you so much for the in-depth review. :)

**Comment by makella** [comment]
redo on the header map
https://team.carto.com/u/mamataakella/builder/64ef4c6a-e4a0-4794-8b65-3ab58ecd5599/embed
